-- Create Role Table
CREATE TABLE role (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE
);

-- Add columns to existing users table
ALTER TABLE users
    ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE users
    ADD COLUMN password VARCHAR(255) NOT NULL;

ALTER TABLE users
    ADD COLUMN username VARCHAR(255) NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

-- Create Join Table for user-role relationship
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE
);

